name: Snyk Security Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Read .terrafrom-version file
      - name: Read .terraform-version
        id: read-tf-version
        run: echo "version=$(cat .terraform-version)" >> $GITHUB_OUTPUT

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ steps.read-tf-version.outputs.version }}

      - name: Set up Snyk
        uses: snyk/actions/setup@master

      - name: Snyk Auth
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk to check Terraform files
        run: snyk iac test --severity-threshold=medium
